"""
thermocouple_k.py

Type-K thermocouple (ITS-90) conversion class with optional
Cold Junction Compensation (CJC) stored per instance.

Usage:
    tc = TypeKThermocouple(cjc_temp_C=25.0)
    hot = tc.mV_to_tC(measured_mV)   # uses built-in CJC
    hot2 = tc.mV_to_tC(measured_mV, cjc_override=5.0)  # override CJC
"""

import numpy as np


class TypeKThermocouple:

    # ===========================================================
    # Static NIST/ITS-90 coefficients
    # ===========================================================
    _k_neg_coeffs = np.array([
        0.0,
        0.394501280250e-01,
        0.236223735980e-04,
       -0.328589067840e-06,
       -0.499048287770e-08,
       -0.675090591730e-10,
       -0.574103274280e-12,
       -0.310888728940e-14,
       -0.104516093650e-16,
       -0.198892668780e-19,
       -0.163226974860e-22
    ])

    _k_pos_coeffs = np.array([
       -0.176004136860e-01,
        0.389212049750e-01,
        0.185587700320e-04,
       -0.994575928740e-07,
        0.318409457190e-09,
       -0.560728448890e-12,
        0.560750590590e-15,
       -0.320207200030e-18,
        0.971511471520e-22,
       -0.121047212750e-25
    ])

    _k_a0 =  0.118597600000e+00
    _k_a1 = -0.118343200000e-03
    _k_a2 =  0.126968600000e+03

    # ===========================================================
    # Shared lookup grid
    # ===========================================================
    _T_GRID = np.linspace(-270.0, 1372.0, 20001)
    _E_GRID = None  # set on first use
    _T_SORTED = None

    @classmethod
    def _init_lookup(cls):
        """Initialize the EMF→temperature lookup table once."""
        if cls._E_GRID is not None:
            return  # already built

        emf = cls._tC_to_mV_poly(cls._T_GRID)
        order = np.argsort(emf)
        cls._E_GRID = emf[order]
        cls._T_SORTED = cls._T_GRID[order]

    # ===========================================================
    # Temp → EMF polynomial
    # ===========================================================
    @classmethod
    def _tC_to_mV_poly(cls, tC):
        """ITS-90 polynomial evaluator used internally."""
        t = np.asarray(tC, dtype=float)
        E = np.zeros_like(t)

        mask_neg = t < 0
        if np.any(mask_neg):
            tt = t[mask_neg]
            val = np.zeros_like(tt)
            for c in reversed(cls._k_neg_coeffs):
                val = val * tt + c
            E[mask_neg] = val

        mask_pos = ~mask_neg
        if np.any(mask_pos):
            tt = t[mask_pos]
            val = np.zeros_like(tt)
            for c in reversed(cls._k_pos_coeffs):
                val = val * tt + c
            val += cls._k_a0 * np.exp(cls._k_a1 * (tt - cls._k_a2)**2)
            E[mask_pos] = val

        return E

    # ===========================================================
    # Instance initialization
    # ===========================================================
    def __init__(self, cjc_temp_C=0.0):
        """
        Initialize a Type-K thermocouple instance.

        Parameters:
            cjc_temp_C : Cold junction temperature in °C
        """
        self.cjc_temp_C = float(cjc_temp_C)

    # ===========================================================
    # Public conversion methods
    # ===========================================================
    def tC_to_mV(self, tC):
        """Temperature (°C) → EMF (mV)."""
        return self._tC_to_mV_poly(tC)

    def mV_to_tC_raw(self, emf_mV):
        """Raw EMF (mV) → temperature (°C) (no CJC)."""
        self._init_lookup()

        emf = np.asarray(emf_mV, dtype=float)
        Emin, Emax = self._E_GRID[0], self._E_GRID[-1]
        emf_clipped = np.clip(emf, Emin, Emax)

        return np.interp(emf_clipped, self._E_GRID, self._T_SORTED)

    def mV_to_tC(self, measured_mV, cjc_override=None):
        """
        Convert measured EMF to temperature USING CJC.

        If cjc_override is provided, it overrides the instance CJC.
        """
        cjc = self.cjc_temp_C if cjc_override is None else cjc_override

        # EMF generated by the cold junction
        cjc_emf = self.tC_to_mV(cjc)

        total_emf = measured_mV + cjc_emf

        return self.mV_to_tC_raw(total_emf)


# ===========================================================
# Optional module test
# ===========================================================
if __name__ == "__main__":
    tc = TypeKThermocouple(cjc_temp_C=25.0)
    print("Self-test:")
    print("CJC =", tc.cjc_temp_C, "°C")
    emf = tc.tC_to_mV(100)
    print("100°C →", emf, "mV →", tc.mV_to_tC(emf), "°C")

    print("\nMeasured 2 mV, CJC=25°C →", tc.mV_to_tC(2.0))
    print("Measured 2 mV, override CJC=5°C →", tc.mV_to_tC(2.0, cjc_override=5.0))
